version: "3.2"

volumes:
  postgres_data: {}
  redis_data: {}

services:
  postgres:
    build: ./docker/postgres
    restart: on-failure
    container_name: ${PROJECT_NAME}_postgres
    image: ${PROJECT_NAME}_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    networks:
      - default_dom5
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"

  backend:
    build:
      dockerfile: ./docker/python/Dockerfile
      context: ./
    restart: on-failure
    container_name: ${PROJECT_NAME}_backend
    image: ${PROJECT_NAME}_backend
    volumes:
      - .:/usr/src/app
    environment:
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - APPEND_SLASH=True
      - PREPEND_WWW=False
      - ENV=local
      - SECURE_SSL_REDIRECT=False
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5433/${PROJECT_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - SESSION_COOKIE_SECURE=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ORIGIN_WHITELIST=localhost:8000,localhost:3005,127.0.0.1:3005,127.0.0.1:8000
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - RQ_HOST=redis
      - RQ_PORT=${DOCKER_REDIS_PORT}
    command: /bin/bash -c "PIPENV_DONT_LOAD_ENV=1 python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - default_dom5
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis

networks:
  default_dom5:
    ipam:
      driver: default
