# Generated by Django 3.1.4 on 2020-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_auth_fields")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        )
    ]
