# Generated by Django 3.1.4 on 2020-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dominion_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
                (
                    "era",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "EA"), (2, "MA"), (3, "LA")]
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dominion_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
                ("commander", models.BooleanField(default=False)),
                ("nations", models.ManyToManyField(to="domdata.Nation")),
            ],
            options={"abstract": False},
        ),
    ]
