# Generated by Django 2.2.12 on 2020-05-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dominion_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dominion_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
                ("general", models.BooleanField(default=True)),
                ("nations", models.ManyToManyField(to="domdata.Nation")),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Commander",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dominion_id",
                    models.PositiveIntegerField(db_index=True, unique=True),
                ),
                ("general", models.BooleanField(default=True)),
                ("nations", models.ManyToManyField(to="domdata.Nation")),
            ],
            options={"abstract": False},
        ),
    ]
