# Generated by Django 3.2 on 2021-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("domdata", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="nation",
            name="modded",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "VANILLA"), (2, "DE"), (3, "DEBUG")], default=1
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="modded",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "VANILLA"), (2, "DE"), (3, "DEBUG")], default=1
            ),
        ),
    ]
